# Configuración del receptor u-blox ZED-F9P (Modo Rover RTK)

# Interfaces de comunicación y asignación de TF
device: /dev/gps_ublox    
frame_id: gps_link      

# Parámetros dinámics del receptor (Filtro de Kalman interno)
dynamic_model: automotive 

# Configuración del puerto serie UART1
uart1:
  baudrate: 460800       

# Tasas de muestreo y navegación (Frecuencia de salida a 10 Hz)
rate: 10               
nav_rate: 1            

# Gestión de memoria y persistencia en el arranque
config_on_startup: false
clear_bbr: false

# Configuración del modo GNSS diferencial (RTK Rover)
tmode3: 0
dgnss_mode: 2

# Configuración de mensajes de salida ROS
publish:
  nav:
    pvt: true
    fix: true
